import 'package:flutter/material.dart';
import 'package:nti_tasks/core/utils/app_colors.dart';

List<Color> listColors = [
  AppColors.green,
  AppColors.blue,
  AppColors.red,
  AppColors.orange,
  AppColors.purple,
  AppColors.yellow,
  AppColors.teal,
  AppColors.cyan,
  AppColors.indigo,
  AppColors.amber,
  AppColors.lime,
  AppColors.deepOrange,
  AppColors.pink,
  AppColors.brown,
  AppColors.grey,
  AppColors.lightBlue,
  AppColors.lightGreen,
  AppColors.deepPurple,
  AppColors.lightGreen,
  AppColors.blueGrey,
  AppColors.blueAccent,
  AppColors.orangeAccent,
  AppColors.purpleAccent,
  AppColors.cyanAccent,
  AppColors.limeAccent,
  AppColors.yellowAccent,
  AppColors.redAccent,
  AppColors.greenAccent,
  AppColors.blue,
  AppColors.orange,
  AppColors.pinkAccent,
  AppColors.green,
];
